import requests
from bs4 import BeautifulSoup
import pycurl
from io import BytesIO
import certifi

JS_ROW_END = "~"
JS_CELL_END = "¬"
JS_INDEX = "÷"
SHAREDINDEXES_SPORT_ID = "SA"
DCAPIPARTICIPANTINDEXES_TEAM_INFO = "PR"
DCAPIPARTICIPANTINDEXES_TEAM_INFO_DELETED = "PRD"
SHAREDINDEXES_TOURNAMENT_NAME = "ZA"
SHAREDINDEXES_EVENT_ID = "AA"
SHAREDINDEXES_MATCH_START_UTIME = "AD"
SHAREDINDEXES_EVENT_STAGE_TYPE_ID = "AB"
SHAREDINDEXES_EVENT_STAGE_ID = "AC"
PLAYER1_NAME = "CX"
LIVE = "AI"
HAS_STATS = "AO"
HOME3CHARNAME = "WM"
AWAY3CHARNAME = "WN"
PLAYER2_NAME = "AF"
HOME_ENCODED_PARTICIPANT_ID = "JA"
AWAY_ENCODED_PARTICIPANT_ID = "JB"
HOME_KEYWORD = "WU"
AWAY_KEYWORD = "WV"
FULLFEEDINDEXES_MOVED_EVENTS_ID = "QA"
SHAREDINDEXES_FEED_SIGNATURE = "A1"
SPORT_SCORE_PART_LIST = 5
SHAREDINDEXES_HOME_RESULT_PERIOD_1 = "BA"
SHAREDINDEXES_HOME_RESULT_PERIOD_2 = "BC"
SHAREDINDEXES_HOME_RESULT_PERIOD_3 = "BE"
SHAREDINDEXES_HOME_RESULT_PERIOD_4 = "BG"
SHAREDINDEXES_HOME_RESULT_PERIOD_5 = "BI"
SHAREDINDEXES_AWAY_RESULT_PERIOD_1 = "BB"
SHAREDINDEXES_AWAY_RESULT_PERIOD_2 = "BD"
SHAREDINDEXES_AWAY_RESULT_PERIOD_3 = "BF"
SHAREDINDEXES_AWAY_RESULT_PERIOD_4 = "BH"
SHAREDINDEXES_AWAY_RESULT_PERIOD_5 = "BJ"
STATS_SET = "HA"
STATS_CATEGORY = "SF"
STATS_PARAMETER = "SG"
STATS_HOME = "SH"
STATS_AWAY = "SI"
POINTS_DETAIL = "HL"
STATS_ENDGAME = "A1"

def getDailyGames(day):
    # Load FlashScore WS with daily matches
    if day == "today":
        url = "https://d.flashscore.es/x/feed/f_2_0_1_es_1"
    else:
        url = "https://d.flashscore.es/x/feed/f_2_1_1_es_1"

    data = BytesIO()
    crl = pycurl.Curl()
    crl.setopt(crl.URL, url)
    crl.setopt(crl.HEADER, 0)
    crl.setopt(crl.TIMEOUT, 30)
    crl.setopt(crl.HTTPHEADER, ["x-fsign: SW9D1eZo"])
    crl.setopt(crl.WRITEFUNCTION, data.write)
    crl.setopt(crl.CAINFO, certifi.where())
    crl.perform()
    crl.close()

    return data.getvalue()
